import Head from 'next/head'
import { useState } from 'react'
import Box from './components/box'
import GraphView from './components/graph-view'
import Searchbar from './components/searchbar'
import RawLocations from '../src/locations.json'
import Location from '../src/location.interface'



export default function Home() {

  const [locations, setLocations] = useState<Array<Location>> (RawLocations)

  return (
    <>
      <Head>
        <title>Temp Data</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {/* Top Bar */}
        <div className='px-5 py-10 flex row-auto justify-between'>
          <h1>Historic Temp</h1>  
          <Searchbar/>
        </div>
        {/* Sidebar */}
        <div>
          {locations.map((location)=>(
            <Box location={location} key={location.locationID}/>
          ))}
        </div>
        {/* Main window */}
        <div> 
          <GraphView />

        </div>
       

      </main>
    </>
  )
}
